AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  SpotFinOpsRoleArn:
    Value: !GetAtt 'SpotFinOpsRole.Arn'
Parameters:
  CostAndUsageBucket:
    Type: String
    Description: The bucket name of where the *HOURLY* Cost and Usage Report is located. https://console.aws.amazon.com/billing/home?#/reports
  RoleName:
    Type: String
    Default: SpotByNetApp_Finops_FullPermissions
  PolicyName:
    Type: String
    Default: SpotByNetApp_Finops_FullPermission_Policy
Resources:
  SpotFinOpsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref 'PolicyName'
      Description: Spot by NetApp Finops Full Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - ec2:Describe*
              - ec2:List*
              - ec2:GetHostReservationPurchasePreview
              - ec2:GetReservedInstancesExchangeQuote
              - ec2:ModifyReservedInstances
              - ec2:AcceptReservedInstancesExchangeQuote
              - ec2:CancelReservedInstancesListing
              - ec2:CreateReservedInstancesListing
              - ec2:PurchaseHostReservation
              - ec2:PurchaseReservedInstancesOffering
              - ec2:PurchaseScheduledInstances
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicyEC2
          - Action:
              - savingsplans:describe*
              - savingsplans:list*
              - savingsplans:CreateSavingsPlan
            Resource:
              - '*'
            Effect: Allow
            Sid: FullPolicySavingsPlans
          - Sid: RequestServiceQuotaIncrease
            Effect: Allow
            Action: servicequotas:RequestServiceQuotaIncrease
            Resource:
              - arn:aws:servicequotas:*:*:ec2/L-D0B7243C
          - Action:
              - aws-portal:ViewBilling
              - aws-portal:ViewUsage
            Resource:
              - '*'
            Effect: Allow
            Sid: BillingdeprecatedJuly6
          - Action:
              - cur:DescribeReportDefinitions
              - cur:PutReportDefinition
              - cur:ModifyReportDefinition
              - ce:Get*
              - ce:Describe*
              - ce:List*
              - account:GetAccountInformation
              - billing:Get*
              - consolidatedbilling:Get*
              - consolidatedbilling:List*
              - invoicing:List*
              - invoicing:Get*
              - cur:Get*
              - cur:Validate*
              - freetier:Get*
              - organizations:List*
              - organizations:DescribeOrganization
              - servicequotas:List*
              - servicequotas:Get*
              - support:*
            Resource:
              - '*'
            Effect: Allow
            Sid: BillingPolicy
          - Action:
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
              - s3:AbortMultipartUpload
              - s3:ListMultipartUploadParts
              - s3:PutObject
              - s3:ListBucket
              - s3:List*
              - s3:PutObjectTagging
              - s3:PutObjectAcl
            Resource: arn:aws:s3:::sc-customer-*
            Effect: Allow
            Sid: S3SyncPermissions
          - Action:
              - s3:ListBucket
              - s3:ListBucketVersions
              - s3:ListBucketMultipartUploads
              - s3:GetBucketLocation
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CostAndUsageBucket'
            Effect: Allow
            Sid: S3CURBucket
          - Action:
              - s3:get*
              - s3:List*
              - s3:Describe*
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref 'CostAndUsageBucket'
                  - /*
            Effect: Allow
            Sid: S3CURObject
  SpotFinOpsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Principal:
              AWS:
                - arn:aws:iam::884866656237:root
                - arn:aws:iam::627743545735:root
            Effect: Allow
      Description: Spot by NetApp FullPermissions Finops IAM Role
      ManagedPolicyArns:
        - !Ref 'SpotFinOpsManagedPolicy'
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      RoleName: !Ref 'RoleName'
