{
 "title": "Spot Ocean",
 "description": "visualizing Ocean metrics, ready to be incorporated into your existing dashboard base",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vng",
    "query": {
     "query": "label_values(ocean_managed_nodes,vng_name)"
    }
   },
   {
    "name": "AZ",
    "query": {
     "query": "label_values(ocean_managed_nodes,az)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ocean Controller Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ocean_controller_heartbeat_info"
    }
   ]
  },
  {
   "title": "vCPU Availability Zone Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (az)(ocean_allocatable_cpu_vcpus{vng_name=~\"$vng\"})"
    }
   ]
  },
  {
   "title": "vCPU instance type Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(vm_type) (ocean_allocatable_cpu_vcpus{vng_name=~\"$vng\",az=~\"$AZ\"})"
    }
   ]
  },
  {
   "title": "vCPU Spot %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(ocean_allocatable_cpu_vcpus{vng_name=~\"$vng\",lifecycle=\"Spot\"})/sum(ocean_allocatable_cpu_vcpus))*100"
    }
   ]
  },
  {
   "title": "Bin Packing Activity Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(ocean_nodes_removed_total{reason=\"scaleDownForOptimization\"}[30m])"
    }
   ]
  },
  {
   "title": "Ocean Metric Exporter Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"count\", kube_pod_container_status_running{container=\"spot-ocean-metric-exporter\"})"
    }
   ]
  },
  {
   "title": "Scale Up Activity Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(ocean_nodes_added_total{reason=\"pendingPodsOrHeadroom\",vng_name=~\"$vng\"}[30m])"
    }
   ]
  }
 ]
}