region                        = "us-west-2"
keypair                       = ""
subnet_ids                    = [""]
security_groups               = [""]
instance_types_ondemand       = "r4.large"
instance_types_spot           = ["r4.xlarge", "r4.2xlarge"]
instance_types_preferred_spot = ["r4.xlarge"]
master_ip                     = ""
spotinst_token                = ""
spotinst_account              = ""